### ISSUE TITLE
Please don't use my code.

### ISSUE THREAD

**Issue by MystPi** [neocruzr/neocruzr#1]
You may not use code from Ninetails unless I explicitly say so.

**Comment by ninjamar** [comment]
ninetails is under the mit license so i'm not sure if you can say this @MystPi 
https://github.com/MystPi/ninetails/blob/main/LICENSE

**Comment by MystPi** [comment]
I guess. I just don't like it very much.

**Comment by ninjamar** [comment]
Change the license then
